spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
      show-sql: true
tlh:
  bms:
    db:
      url: jdbc:postgresql://localhost:5432/tlh-bms
      username: postgres
      password: sandu